version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    ports:
      - "${VITE_PORT:-4001}:4001"
    env_file:
      - ./frontend/.env 
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev 

