name: CI - Test Frontend and Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    name: 🧪 Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Fix permission for node_modules binaries
        run: chmod +x ./node_modules/.bin/*

      - name: Run backend tests
        run: npm test

  test-frontend:
    name: 🧪 Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test
