name: CI - Docker Compose Full Stack Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Create .env for backend
        run: cp backend/.env.example backend/.env

      - name: Create .env for frontend
        run: cp frontend/.env.example frontend/.env

      - name: Build and run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d
          sleep 10

      - name: Check backend health
        run: curl -f http://localhost:4000/ping || (docker-compose logs backend && exit 1)

      - name: Check frontend health
        run: curl -f http://localhost:4001 || (docker-compose logs frontend && exit 1)

      - name: Show backend logs
        run: docker-compose logs backend

      - name: Show frontend logs
        run: docker-compose logs frontend

      - name: Shut down
        run: docker-compose down -v
