# .github/workflows/docker-test.yml
name: Docker Backend Build & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend-test ./backend

      - name: Run container
        run: |
          docker run -d --name backend-container -p 4000:4000 backend-test
          sleep 5
          docker logs backend-container

      - name: Curl health check
        run: curl -f http://localhost:4000 || (docker logs backend-container && exit 1)
